defaults: &default_steps
  steps:
  - checkout
  - run:
      name: Job step 01
      command: date
  - run:
      name: Job step 02 Print Enviroment variable
      command: echo $consumer_key
  - run:
      name: Touch file
      command: touch file_test.txt
  - run:
      name: LS
      command: ls -la
  - run:
      name: "Default Steps 01 command 01...."
      command: echo step 01
  - run:
      name: "Default Steps 02 command 02...."
      command: echo step 02

version: 2
jobs:
  build-my-project:
    docker:
    - image: debian:stretch
    <<: *default_steps

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build-my-project
      requires:
        filters:
          branches:
            only: master

