defaults: &default_steps
  steps:
  - checkout
  - run:
      name: "Install NodeJS"
      command: |
        set +e
        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
        export NVM_DIR="/opt/circleci/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install v6.2.2
        nvm alias default v6.2.2

        # Each step uses the same `$BASH_ENV`, so need to modify it
        echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
        echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV

version: 2
jobs:
  build-my-project-container:
    docker:
    - image: debian:stretch
    <<: *default_steps

  deploy-my-project:
    machine:
      enabled: true
    environment:
      SERVICE_NAME: text-summarization
      ORG: singnet
      DOCKER_ORG: singularitynet
      SNETD_PORT: 6207
      SNETD_CONFIG: config/snetd_text_summarization_server_config.json
    steps:
    - run:
        name: Deploy Over SSH
        command: echo Deployyyy
    - run:
        name: Check Node Version
        command: node --version

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-my-project-container
      - deploy-my-project:
          requires:
            - build-my-project-container
          filters:
            branches:
              only: master