defaults: &default_steps
  steps:
  - checkout
  - run:
      name: "Install NodeJS"
      command: apt install nodejs -y

version: 2
jobs:
  build-my-project-container:
    docker:
    - image: debian:stretch
    <<: *default_steps

  deploy-my-project:
    machine:
      enabled: true
    environment:
      SERVICE_NAME: text-summarization
      ORG: singnet
      DOCKER_ORG: singularitynet
      SNETD_PORT: 6207
      SNETD_CONFIG: config/snetd_text_summarization_server_config.json
    steps:
    - run:
        name: Deploy Over SSH
        command: echo Deployyyy
    - run:
        name: Check Node Version
        command: node --version

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-my-project-container
      - deploy-my-project:
          requires:
            - build-my-project-container
          filters:
            branches:
              only: master